### ISSUE TITLE
Setting tools issue in Travis CI

### ISSUE THREAD

**Issue by thotayashwanth123** [coala/coala-eclipse#31]
Setting tools is not allowing Travis CI to pass.
https://travis-ci.org/coala/coala-eclipse/builds/197575995#L591

**Comment by aashutoshrathi** [comment]
This can be fixed using 
```
python -m pip install --upgrade pip
pip install --upgrade setuptools
```
but this no longer is the only reason that is not allowing Travis to pass,
we have one more error.
```
"mvn -X -Dtycho.disableP2Mirrors=true clean verify" exited with 1
```

**Comment by jayvdb** [comment]
I suspect "Setting tools" in issue description should be "setuptools", as that is what is reporting an error in the travis log mentioned.

```
sudo pip3 install -U pip setuptools virtualenvwrapper
Downloading/unpacking pip from https://pypi.python.org/packages/b6/ac/7015eb97dc749283ffdec1c3a88ddb8ae03b8fad0f0e611408f196358da3/pip-9.0.1-py2.py3-none-any.whl#md5=297dbd16ef53bcef0447d245815f5144
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB): 1.3MB downloaded
Downloading/unpacking setuptools from https://pypi.python.org/packages/a7/62/3995dc3067cbf8d4a13ddac0f87417b9a08799c586b3faa77d62ad9085de/setuptools-34.1.0-py2.py3-none-any.whl#md5=3bd30e82a4371d5fe236c9e412d7b9c6
  Downloading setuptools-34.1.0-py2.py3-none-any.whl (389kB): 389kB downloaded
Downloading/unpacking virtualenvwrapper
  Downloading virtualenvwrapper-4.7.2.tar.gz (90kB): 90kB downloaded
  Running setup.py (path:/tmp/pip_build_root/virtualenvwrapper/setup.py) egg_info for package virtualenvwrapper
    
    Installed /tmp/pip_build_root/virtualenvwrapper/pbr-1.10.0-py3.4.egg
    [pbr] Processing SOURCES.txt
    warning: LocalManifestMaker: standard file '-c' not found
    
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files found matching '.gitreview'
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
    warning: no files found matching '*.png' under directory 'docs'
Downloading/unpacking packaging>=16.8 (from setuptools)
  Downloading packaging-16.8-py2.py3-none-any.whl
Downloading/unpacking six>=1.6.0 (from setuptools)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking appdirs>=1.4.0 (from setuptools)
  Downloading appdirs-1.4.0-py2.py3-none-any.whl
Downloading/unpacking virtualenv (from virtualenvwrapper)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB): 1.8MB downloaded
Downloading/unpacking virtualenv-clone (from virtualenvwrapper)
  Downloading virtualenv-clone-0.2.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/virtualenv-clone/setup.py) egg_info for package virtualenv-clone
    
Downloading/unpacking stevedore (from virtualenvwrapper)
  Downloading stevedore-1.20.0-py2.py3-none-any.whl
Downloading/unpacking pyparsing (from packaging>=16.8->setuptools)
  Downloading pyparsing-2.1.10-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking pbr>=1.8 (from stevedore->virtualenvwrapper)
  Downloading pbr-1.10.0-py2.py3-none-any.whl (96kB): 96kB downloaded
Installing collected packages: pip, setuptools, virtualenvwrapper, packaging, six, appdirs, virtualenv, virtualenv-clone, stevedore, pyparsing, pbr
  Found existing installation: pip 1.5.4
    Not uninstalling pip at /usr/lib/python3/dist-packages, owned by OS
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python3/dist-packages, owned by OS
  Running setup.py install for virtualenvwrapper
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named 'packaging'
    Complete output from command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/virtualenvwrapper/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nu0v4u0i-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/local/lib/python3.4/dist-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 70, in <module>
    import packaging.version
ImportError: No module named 'packaging'
----------------------------------------
Cleaning up...
Command /usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/virtualenvwrapper/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-nu0v4u0i-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/virtualenvwrapper
Storing debug log for failure in /home/travis/.pip/pip.log
The command "sudo pip3 install -U pip setuptools virtualenvwrapper" failed and exited with 1 during .
```

**Comment by jayvdb** [comment]
This problem was fixed upstream in `setuptools`, I believe.

It is not occurring at the moment.

**Comment by jayvdb** [comment]
Note however that there is a different problem preventing progress
https://github.com/coala/coala-eclipse/issues/49
