### ISSUE TITLE
Fix broken tests

### ISSUE THREAD

**Issue by yukiisbored** [coala/coala-eclipse#44]
There's a test failing which is blocking PRs and further contributions to this project. A fix or temporary workaround is needed before GCI.

https://travis-ci.org/coala/coala-eclipse

**Comment by manankalra** [comment]
@yukiisbored I'm a newcomer and just opened a PR in this repo. Just wanted to know if there's any progress on this.

**Comment by yukiisbored** [comment]
@manankalra Hey, very little progress is made due to time constraints. I'm gonna unassign myself from this.

**Comment by manankalra** [comment]
I can take this issue if you can guide me a little on what needs to be done. :)

**Comment by anctartica** [comment]
I want to try and fix this... can you assign this to me? @yukiisbored

**Comment by jayvdb** [comment]
https://github.com/coala/coala-eclipse/issues/51 is likely to be helpful to find and fix this bug.

**Comment by jayvdb** [comment]
Current log of the test failure
https://travis-ci.org/coala/coala-eclipse/builds/394379974

**Comment by saksham189** [comment]
The RunCmdTest is throwing error:
```
Running com.coala.core.tests.RunCmdTest while calling 
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.011 sec <<< FAILURE! - in com.coala.core.tests.RunCmdTest
test(com.coala.core.tests.RunCmdTest)  Time elapsed: 3.011 sec  <<< ERROR!
org.apache.commons.exec.ExecuteException: Process exited with an error: 255 (Exit value: 255)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at com.coala.core.utils.ExternalUtils.getAvailableBears(ExternalUtils.java:188)
	at com.coala.core.utils.ExternalUtils.getBearSettings(ExternalUtils.java:195)
	at com.coala.core.utils.ExternalUtils.runBearOnFile(ExternalUtils.java:55)
	at com.coala.core.tests.RunCmdTest.test(RunCmdTest.java:58)
```

The `getAvailableBears` method shown below runs `coala -B --json` which must be throwing error because of this issue: https://github.com/coala/coala/issues/4881

```
public static JSONArray getAvailableBears() throws ExecuteException, IOException {
    CommandLine cmdLine = new CommandLine("coala");
    cmdLine.addArgument("--json");
    cmdLine.addArgument("-B");
    final ByteArrayOutputStream stdout = new ByteArrayOutputStream();
    PumpStreamHandler pumpStreamHandler = new PumpStreamHandler(stdout, null);
    Executor executor = new DefaultExecutor();
    executor.setStreamHandler(pumpStreamHandler);
    executor.execute(cmdLine);
    JSONArray bearList = new JSONObject(stdout.toString()).getJSONArray("bears");
    return bearList;
  }
```
